package FinalProject;

import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        
        pack();
        //here to add any @Override
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginBG = new javax.swing.JPanel();
        showPassword = new javax.swing.JRadioButton();
        tfEmail = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        lDontHaveAnAccount = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lTitleText = new javax.swing.JLabel();
        lPressToSignIn = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        BGimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Menu");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("Login Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        panelLoginBG.setBackground(new java.awt.Color(62, 62, 62));
        panelLoginBG.setLayout(null);

        showPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showPasswordItemStateChanged(evt);
            }
        });
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        panelLoginBG.add(showPassword);
        showPassword.setBounds(380, 230, 20, 20);

        tfEmail.setBackground(new java.awt.Color(62, 62, 62));
        tfEmail.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        tfEmail.setText("user@gmail.com");
        panelLoginBG.add(tfEmail);
        tfEmail.setBounds(70, 150, 340, 40);

        tfPassword.setBackground(new java.awt.Color(62, 62, 62));
        tfPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        tfPassword.setForeground(new java.awt.Color(255, 255, 255));
        tfPassword.setText("jPasswordField1");
        panelLoginBG.add(tfPassword);
        tfPassword.setBounds(70, 220, 340, 40);

        lDontHaveAnAccount.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lDontHaveAnAccount.setForeground(new java.awt.Color(255, 255, 255));
        lDontHaveAnAccount.setText("Dont have an account?");
        panelLoginBG.add(lDontHaveAnAccount);
        lDontHaveAnAccount.setBounds(70, 270, 150, 20);

        lPassword.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lPassword.setForeground(new java.awt.Color(255, 255, 255));
        lPassword.setText("Password:");
        panelLoginBG.add(lPassword);
        lPassword.setBounds(70, 205, 80, 20);

        lEmail.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lEmail.setForeground(new java.awt.Color(255, 255, 255));
        lEmail.setText("Email:");
        panelLoginBG.add(lEmail);
        lEmail.setBounds(70, 135, 80, 20);

        lTitleText.setFont(new java.awt.Font("Consolas", 0, 35)); // NOI18N
        lTitleText.setForeground(new java.awt.Color(255, 255, 255));
        lTitleText.setText("Welcome back to ZBank!");
        panelLoginBG.add(lTitleText);
        lTitleText.setBounds(60, 20, 430, 40);

        lPressToSignIn.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lPressToSignIn.setForeground(new java.awt.Color(102, 204, 255));
        lPressToSignIn.setText("Sign-in");
        lPressToSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPressToSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lPressToSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lPressToSignInMouseExited(evt);
            }
        });
        panelLoginBG.add(lPressToSignIn);
        lPressToSignIn.setBounds(210, 270, 50, 20);

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLoginBG.add(btnLogin);
        btnLogin.setBounds(100, 350, 270, 40);

        BGimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/500x500_loginBG.png"))); // NOI18N
        BGimage.setText("Login");
        panelLoginBG.add(BGimage);
        BGimage.setBounds(0, 0, 500, 490);

        getContentPane().add(panelLoginBG);
        panelLoginBG.setBounds(0, 0, 500, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //YESSIR!
        //database na ni dria na part
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void showPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showPasswordItemStateChanged
        // TODO add your handling code here:
        if (showPassword.isSelected()) {
            tfPassword.setEchoChar((char) 0); // Show password
        } else {
            tfPassword.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_showPasswordItemStateChanged

    private void lPressToSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPressToSignInMouseClicked
        // TODO add your handling code here:
        toSignUp();
    }//GEN-LAST:event_lPressToSignInMouseClicked

    private void lPressToSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPressToSignInMouseEntered
        // TODO add your handling code here:
        lPressToSignIn.setText("<html><u>Sign-up</u></html>");
    }//GEN-LAST:event_lPressToSignInMouseEntered

    private void lPressToSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPressToSignInMouseExited
        // TODO add your handling code here:
        lPressToSignIn.setText("Sign-up");
    }//GEN-LAST:event_lPressToSignInMouseExited

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    //This is amazing lol
    private void toSignUp(){
        SignUp signUp = new SignUp();
        signUp.setVisible(true);
        this.dispose();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGimage;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lDontHaveAnAccount;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lPressToSignIn;
    private javax.swing.JLabel lTitleText;
    private javax.swing.JPanel panelLoginBG;
    private javax.swing.JRadioButton showPassword;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
