package FinalProject;

public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSignInBG = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        rbShowConfirmPassword = new javax.swing.JRadioButton();
        rbShowPassword = new javax.swing.JRadioButton();
        lCreateAnAccount = new javax.swing.JLabel();
        lFirstName = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        lMiddleName = new javax.swing.JLabel();
        tfMiddelName = new javax.swing.JTextField();
        lLastName = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        lCreateAnAccount1 = new javax.swing.JLabel();
        lRegion = new javax.swing.JLabel();
        tfRegion = new javax.swing.JTextField();
        lMunicipalOrCity = new javax.swing.JLabel();
        tfMunicipalOrCity = new javax.swing.JTextField();
        lPurokStreetOrBarangay = new javax.swing.JLabel();
        tfPurokStreetOrBarangay = new javax.swing.JTextField();
        lOtherInformation = new javax.swing.JLabel();
        lAge = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        cbMonth = new javax.swing.JComboBox<>();
        cbDay = new javax.swing.JComboBox<>();
        cbYear = new javax.swing.JComboBox<>();
        lBirthdate = new javax.swing.JLabel();
        lBirthplace = new javax.swing.JLabel();
        tfBirthplace = new javax.swing.JTextField();
        lPurokStreetOrBarangay2 = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        lConfirmPassword = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        lLoginInfo = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();
        lAlreadyHaveAnAccount = new javax.swing.JLabel();
        lPressToSignIn = new javax.swing.JLabel();
        tfCreatePassword = new javax.swing.JPasswordField();
        tfConfirmPassword = new javax.swing.JPasswordField();
        BGImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign-Up Menu");
        setMaximumSize(new java.awt.Dimension(650, 650));
        setMinimumSize(new java.awt.Dimension(650, 650));
        setName("Sign In Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        panelSignInBG.setLayout(null);

        lTitle.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        lTitle.setForeground(new java.awt.Color(255, 255, 255));
        lTitle.setText("Welcome new user!");
        panelSignInBG.add(lTitle);
        lTitle.setBounds(100, 50, 440, 40);

        rbShowConfirmPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbShowConfirmPasswordItemStateChanged(evt);
            }
        });
        panelSignInBG.add(rbShowConfirmPassword);
        rbShowConfirmPassword.setBounds(250, 500, 20, 30);

        rbShowPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbShowPasswordItemStateChanged(evt);
            }
        });
        panelSignInBG.add(rbShowPassword);
        rbShowPassword.setBounds(250, 440, 20, 30);

        lCreateAnAccount.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lCreateAnAccount.setForeground(new java.awt.Color(255, 255, 255));
        lCreateAnAccount.setText("Profile");
        panelSignInBG.add(lCreateAnAccount);
        lCreateAnAccount.setBounds(110, 130, 80, 20);

        lFirstName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lFirstName.setText("First Name");
        panelSignInBG.add(lFirstName);
        lFirstName.setBounds(40, 150, 90, 20);

        tfFirstName.setBackground(new java.awt.Color(102, 102, 102));
        tfFirstName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfFirstName.setForeground(new java.awt.Color(255, 255, 255));
        tfFirstName.setText("Ervon Rey");
        panelSignInBG.add(tfFirstName);
        tfFirstName.setBounds(40, 170, 230, 30);

        lMiddleName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lMiddleName.setForeground(new java.awt.Color(255, 255, 255));
        lMiddleName.setText("Middle Name");
        panelSignInBG.add(lMiddleName);
        lMiddleName.setBounds(40, 210, 88, 20);

        tfMiddelName.setBackground(new java.awt.Color(102, 102, 102));
        tfMiddelName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfMiddelName.setForeground(new java.awt.Color(255, 255, 255));
        tfMiddelName.setText("Quinones");
        panelSignInBG.add(tfMiddelName);
        tfMiddelName.setBounds(40, 230, 230, 30);

        lLastName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lLastName.setForeground(new java.awt.Color(255, 255, 255));
        lLastName.setText("Last Name");
        panelSignInBG.add(lLastName);
        lLastName.setBounds(40, 270, 80, 20);

        tfLastName.setBackground(new java.awt.Color(102, 102, 102));
        tfLastName.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfLastName.setForeground(new java.awt.Color(255, 255, 255));
        tfLastName.setText("Mellisa");
        panelSignInBG.add(tfLastName);
        tfLastName.setBounds(40, 290, 230, 30);

        lCreateAnAccount1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lCreateAnAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lCreateAnAccount1.setText("Address");
        panelSignInBG.add(lCreateAnAccount1);
        lCreateAnAccount1.setBounds(380, 340, 80, 20);

        lRegion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lRegion.setForeground(new java.awt.Color(255, 255, 255));
        lRegion.setText("Region");
        panelSignInBG.add(lRegion);
        lRegion.setBounds(290, 360, 50, 20);

        tfRegion.setBackground(new java.awt.Color(102, 102, 102));
        tfRegion.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfRegion.setForeground(new java.awt.Color(255, 255, 255));
        tfRegion.setText("Davao del Sur");
        tfRegion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfRegionMouseEntered(evt);
            }
        });
        panelSignInBG.add(tfRegion);
        tfRegion.setBounds(290, 380, 300, 30);

        lMunicipalOrCity.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lMunicipalOrCity.setForeground(new java.awt.Color(255, 255, 255));
        lMunicipalOrCity.setText("Municipality / City");
        panelSignInBG.add(lMunicipalOrCity);
        lMunicipalOrCity.setBounds(290, 420, 160, 20);

        tfMunicipalOrCity.setBackground(new java.awt.Color(102, 102, 102));
        tfMunicipalOrCity.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfMunicipalOrCity.setForeground(new java.awt.Color(255, 255, 255));
        tfMunicipalOrCity.setText("Magsaysay");
        panelSignInBG.add(tfMunicipalOrCity);
        tfMunicipalOrCity.setBounds(290, 440, 300, 30);

        lPurokStreetOrBarangay.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lPurokStreetOrBarangay.setForeground(new java.awt.Color(255, 255, 255));
        lPurokStreetOrBarangay.setText("Purok/Street with Barangay");
        panelSignInBG.add(lPurokStreetOrBarangay);
        lPurokStreetOrBarangay.setBounds(290, 480, 210, 20);

        tfPurokStreetOrBarangay.setBackground(new java.awt.Color(102, 102, 102));
        tfPurokStreetOrBarangay.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfPurokStreetOrBarangay.setForeground(new java.awt.Color(255, 255, 255));
        tfPurokStreetOrBarangay.setText("Purok 1-B, Bacungan");
        panelSignInBG.add(tfPurokStreetOrBarangay);
        tfPurokStreetOrBarangay.setBounds(290, 500, 300, 30);

        lOtherInformation.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lOtherInformation.setForeground(new java.awt.Color(255, 255, 255));
        lOtherInformation.setText("Other Information");
        panelSignInBG.add(lOtherInformation);
        lOtherInformation.setBounds(340, 130, 180, 20);

        lAge.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lAge.setForeground(new java.awt.Color(255, 255, 255));
        lAge.setText("Age");
        panelSignInBG.add(lAge);
        lAge.setBounds(300, 150, 30, 20);

        tfAge.setBackground(new java.awt.Color(102, 102, 102));
        tfAge.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfAge.setForeground(new java.awt.Color(255, 255, 255));
        tfAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfAgeMouseEntered(evt);
            }
        });
        panelSignInBG.add(tfAge);
        tfAge.setBounds(290, 170, 50, 30);

        cbMonth.setBackground(new java.awt.Color(102, 102, 102));
        cbMonth.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbMonth.setForeground(new java.awt.Color(255, 255, 255));
        cbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        panelSignInBG.add(cbMonth);
        cbMonth.setBounds(350, 170, 75, 30);

        cbDay.setBackground(new java.awt.Color(102, 102, 102));
        cbDay.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbDay.setForeground(new java.awt.Color(255, 255, 255));
        cbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        panelSignInBG.add(cbDay);
        cbDay.setBounds(430, 170, 72, 30);

        cbYear.setBackground(new java.awt.Color(102, 102, 102));
        cbYear.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cbYear.setForeground(new java.awt.Color(255, 255, 255));
        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        panelSignInBG.add(cbYear);
        cbYear.setBounds(510, 170, 80, 30);

        lBirthdate.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lBirthdate.setForeground(new java.awt.Color(255, 255, 255));
        lBirthdate.setText("Birthdate");
        panelSignInBG.add(lBirthdate);
        lBirthdate.setBounds(420, 150, 80, 20);

        lBirthplace.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lBirthplace.setForeground(new java.awt.Color(255, 255, 255));
        lBirthplace.setText("Birthplace");
        panelSignInBG.add(lBirthplace);
        lBirthplace.setBounds(290, 210, 210, 20);

        tfBirthplace.setBackground(new java.awt.Color(102, 102, 102));
        tfBirthplace.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfBirthplace.setForeground(new java.awt.Color(255, 255, 255));
        panelSignInBG.add(tfBirthplace);
        tfBirthplace.setBounds(290, 230, 300, 30);

        lPurokStreetOrBarangay2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lPurokStreetOrBarangay2.setForeground(new java.awt.Color(255, 255, 255));
        lPurokStreetOrBarangay2.setText("Phone Number");
        panelSignInBG.add(lPurokStreetOrBarangay2);
        lPurokStreetOrBarangay2.setBounds(290, 270, 100, 20);

        tfPhoneNumber.setBackground(new java.awt.Color(102, 102, 102));
        tfPhoneNumber.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        panelSignInBG.add(tfPhoneNumber);
        tfPhoneNumber.setBounds(290, 290, 300, 30);

        lConfirmPassword.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lConfirmPassword.setText("Confirm Password");
        panelSignInBG.add(lConfirmPassword);
        lConfirmPassword.setBounds(40, 480, 140, 20);

        lPassword.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lPassword.setForeground(new java.awt.Color(255, 255, 255));
        lPassword.setText("Password");
        panelSignInBG.add(lPassword);
        lPassword.setBounds(40, 420, 64, 20);

        tfEmail.setBackground(new java.awt.Color(102, 102, 102));
        tfEmail.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tfEmail.setForeground(new java.awt.Color(255, 255, 255));
        panelSignInBG.add(tfEmail);
        tfEmail.setBounds(40, 380, 230, 30);

        lEmail.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lEmail.setForeground(new java.awt.Color(255, 255, 255));
        lEmail.setText("Email");
        panelSignInBG.add(lEmail);
        lEmail.setBounds(40, 360, 90, 20);

        lLoginInfo.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lLoginInfo.setForeground(new java.awt.Color(255, 255, 255));
        lLoginInfo.setText("Create Account");
        panelSignInBG.add(lLoginInfo);
        lLoginInfo.setBounds(80, 340, 150, 20);

        btnCancel.setBackground(new java.awt.Color(62, 62, 62));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        panelSignInBG.add(btnCancel);
        btnCancel.setBounds(300, 550, 120, 30);

        btnCreateAccount.setBackground(new java.awt.Color(62, 62, 62));
        btnCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setText("Create Account");
        panelSignInBG.add(btnCreateAccount);
        btnCreateAccount.setBounds(430, 550, 120, 30);

        lAlreadyHaveAnAccount.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lAlreadyHaveAnAccount.setForeground(new java.awt.Color(255, 255, 255));
        lAlreadyHaveAnAccount.setText("Already have an account?");
        panelSignInBG.add(lAlreadyHaveAnAccount);
        lAlreadyHaveAnAccount.setBounds(40, 540, 200, 20);

        lPressToSignIn.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        lPressToSignIn.setForeground(new java.awt.Color(102, 204, 255));
        lPressToSignIn.setText("Login");
        lPressToSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPressToSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lPressToSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lPressToSignInMouseExited(evt);
            }
        });
        panelSignInBG.add(lPressToSignIn);
        lPressToSignIn.setBounds(240, 540, 50, 20);

        tfCreatePassword.setBackground(new java.awt.Color(102, 102, 102));
        tfCreatePassword.setForeground(new java.awt.Color(255, 255, 255));
        panelSignInBG.add(tfCreatePassword);
        tfCreatePassword.setBounds(40, 440, 230, 30);

        tfConfirmPassword.setBackground(new java.awt.Color(102, 102, 102));
        tfConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        panelSignInBG.add(tfConfirmPassword);
        tfConfirmPassword.setBounds(40, 500, 230, 30);

        BGImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePack/650x650_SignInBG.png"))); // NOI18N
        panelSignInBG.add(BGImage);
        BGImage.setBounds(0, 0, 650, 650);

        getContentPane().add(panelSignInBG);
        panelSignInBG.setBounds(0, 0, 650, 650);

        getAccessibleContext().setAccessibleName("Sign In Menu");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfRegionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRegionMouseEntered
        // TODO add your handling code here:
        if (tfRegion.equals("example: Davao del Sur")){
            tfRegion.setText("");
        }
    }//GEN-LAST:event_tfRegionMouseEntered

    private void tfAgeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAgeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeMouseEntered

    private void lPressToSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPressToSignInMouseClicked
        // TODO add your handling code here:
        toLogin();
    }//GEN-LAST:event_lPressToSignInMouseClicked

    private void lPressToSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPressToSignInMouseEntered
        // TODO add your handling code here:
        lPressToSignIn.setText("<html><u>Login</u></html>");
    }//GEN-LAST:event_lPressToSignInMouseEntered

    private void lPressToSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPressToSignInMouseExited
        // TODO add your handling code here:
        lPressToSignIn.setText("Login");
    }//GEN-LAST:event_lPressToSignInMouseExited

    private void rbShowPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbShowPasswordItemStateChanged
        // TODO add your handling code here:
        if (rbShowPassword.isSelected()) {
            tfCreatePassword.setEchoChar((char) 0); // Show password
        } else {
            tfCreatePassword.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_rbShowPasswordItemStateChanged

    private void rbShowConfirmPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbShowConfirmPasswordItemStateChanged
        // TODO add your handling code here:
        if (rbShowConfirmPassword.isSelected()) {
            tfConfirmPassword.setEchoChar((char) 0); // Show password
        } else {
            tfConfirmPassword.setEchoChar('*'); // Hide password
        }
        
    }//GEN-LAST:event_rbShowConfirmPasswordItemStateChanged

    /**
     * @param args the command line arguments
     */
    
    private void toLogin(){
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGImage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JComboBox<String> cbDay;
    private javax.swing.JComboBox<String> cbMonth;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel lAge;
    private javax.swing.JLabel lAlreadyHaveAnAccount;
    private javax.swing.JLabel lBirthdate;
    private javax.swing.JLabel lBirthplace;
    private javax.swing.JLabel lConfirmPassword;
    private javax.swing.JLabel lCreateAnAccount;
    private javax.swing.JLabel lCreateAnAccount1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFirstName;
    private javax.swing.JLabel lLastName;
    private javax.swing.JLabel lLoginInfo;
    private javax.swing.JLabel lMiddleName;
    private javax.swing.JLabel lMunicipalOrCity;
    private javax.swing.JLabel lOtherInformation;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lPressToSignIn;
    private javax.swing.JLabel lPurokStreetOrBarangay;
    private javax.swing.JLabel lPurokStreetOrBarangay2;
    private javax.swing.JLabel lRegion;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel panelSignInBG;
    private javax.swing.JRadioButton rbShowConfirmPassword;
    private javax.swing.JRadioButton rbShowPassword;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfBirthplace;
    private javax.swing.JPasswordField tfConfirmPassword;
    private javax.swing.JPasswordField tfCreatePassword;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfMiddelName;
    private javax.swing.JTextField tfMunicipalOrCity;
    private javax.swing.JTextField tfPhoneNumber;
    private javax.swing.JTextField tfPurokStreetOrBarangay;
    private javax.swing.JTextField tfRegion;
    // End of variables declaration//GEN-END:variables
}
